logging:
  level:
    root: info
    org.hiberante.SQL: debug
    org.hiberante.type: trace

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

    hibernate:
      ddl-auto: update

  profiles:
    active: local, jwt

springdoc:
  packages-to-scan: com.pop.planu
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
  api-docs:
    path: /api-docs

jwt:
  secret: 'hello-openAPI-hello-princesses-secret-key'
  expiration-time: 30 # 30분